sudo: required

services:
    - docker

before_install:
    - docker build -t satishgh/dockerreact -f Dockerfile.dev .

script:
    - docker run -e CI=true satishgh/dockerreact npm run test

deploy: 
    skip_cleanup: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "dockerreact"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-2-308347247631"
    bucket_path: "dockerreact"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"