version: '3'

services: 
    reactapp:
        build:
            context: .
            dockerfile: Dockerfile.dev
        
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
        stdin_open: 
            true
    
    reacttest:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        command: 
            ["npm", "run", "test"]
        
        stdin_open: 
            true